services:
  server:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    command: sh -c "pip install -r requirements.txt && flask run --host=0.0.0.0 --port=5000"
  
  client:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    command: python -m http.server 3000
